photos/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^new/', views.new_photo),
    url(r'^(?P<photo_id>\d+)$', views.single_photo, name='view_single_photo'),
]

profiles/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        r'^(?P<username>[\w.@+-]+)/$',
        views.profile,
        name='profile'
    ),
]

pystagram/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views  # 이 줄 추가.

urlpatterns = patterns(
    '',
    # Examples:
    url(r'^$', 'pystagram.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin[a-z0-9]/', include(admin.site.urls)),

    url(r'^photos/', include('photos.urls')),

    url(r'^users/', include('profiles.urls')),

    url(
        r'^accounts/login/', auth_views.login, name='login',
        kwargs={
            'template_name': 'login.html'
        }
    ),
    url(
        r'^accounts/logout/', auth_views.logout, name='logout',
        kwargs={
            'next_page': settings.LOGIN_URL,
        }
    ),

    url('', include('social.apps.django_app.urls', namespace='social')),
)

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

photos/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.core.urlresolvers import reverse_lazy
from django.conf import settings

# Create your models here.
class Photo(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    image_file = models.ImageField(upload_to='%Y/%m/%d')
    filtered_image_file = models.ImageField(upload_to='static_files/uploaded/%Y/%m/%d')
    description = models.TextField(max_length=500, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def delete(self, *args, **kwargs):
        self.image_file.delete()
        self.filtered_image_file.delete()
        super(Photo, self).delete(*args, **kwargs)

    def get_absolute_url(self):
        return reverse_lazy('view_single_photo', kwargs={'photo_id': self.id})

profiles/models.py
from django.db import models

# Create your models here.

photos/forms.py
# coding: utf-8

from __future__ import unicode_literals
from django import forms
from photos.models import Photo

class PhotoEditForm(forms.ModelForm):
	class Meta:
		model = Photo
		fields = ('image_file', 'description',)

photos/views.py
# coding: utf-8

from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse

from photos.models import Photo
from .forms import PhotoEditForm


def single_photo(request, photo_id):
    photo = get_object_or_404(Photo, pk=photo_id)

    return render(
        request,
        'photo.html',
        {
            'photo': photo,
        }
    )

def new_photo(request):
    if request.method == "GET":
        edit_form = PhotoEditForm()
    elif request.method == "POST":
        edit_form = PhotoEditForm(request.POST, request.FILES)

        if edit_form.is_valid():
            new_photo = edit_form.save()

            return redirect(new_photo.get_absolute_url())

    return render(
        request,
        'new_photo.html',
        {
            'form': edit_form,
        }
    )

profiles/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import get_user_model


def profile(request, username):
    User = get_user_model()
    user = get_object_or_404(User, username=username)
    ctx = {
        'user': user,
    }

    return render(request, 'profile.html', ctx)

pystagram/views.py
# coding: utf-8

from django.shortcuts import render


def home(request):
    return render(request,'home.html')

profiles/templates/profile.html
{% extends 'layout.html' %}
{% block content %}
<h1>님의 프로필 페이지</h1>

<ul>
{% for photo in user.photo_set.all %}

    <li><img src="{{ photo.image_file.url }}" /></li>
{% empty %}
    <li>게시한 사진이 없습니다.</li>
{% endfor %}
</ul>
{% endblock %}

templates/hi.html
{% block hi %}
    나는 footer이얌
{% endblock %}

templates/home.html
{% extends "layout2.html" %}

{% block content %}
    <br>
    <div>PYSTAGRAM에 오신것을 환영하오 낯선이여</div>
    <br>
{% endblock %}

templates/layout.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <title></title>
    <meta charset="utf-8">
    <script type="text/javascript" src="{% static 'js/jquery-2.1.3.min.js' %}"></script>
</head>

<body>
{% block content %}안녕{% endblock %}
</body>

</html>

templates/layout2.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <title>PYSTAGRAM</title>
    <meta charset="utf-8">
    <script type="text/javascript" src="{% static 'js/jquery-2.1.3.min.js' %}"></script>
</head>

<header>
    {% block loginstatus %}
        {% include "loginstatus.html" %}
    {% endblock %}

</header>

<body>
{% block content %}안녕{% endblock %}
</body>

</html>

templates/login.html
{% extends "layout2.html" %}

{% block content %}

    {% if form.errors %}
        <p>ID나 비밀번호가 일치하지 않습니다.</p>
    {% endif %}

    <form method="post" action="{% url 'login' %}">
        {% csrf_token %}
        <table>
            <tr>
                <td>{{ form.username.label_tag }}</td>
                <td>{{ form.username }}</td>
            </tr>
            <tr>
                <td>{{ form.password.label_tag }}</td>
                <td>{{ form.password }}</td>
            </tr>
        </table>

        <input type="hidden" name="next" value="{{ next }}" />


        <button type="submit">로그인</button>
    </form>

{% endblock %}

templates/loginstatus.html
<h1>hi</h1>
<ul>

    authen : {{ user.is_authenticated }}
<br>
    active : {{ user.is_active }}
    {% if user.is_authenticated %}
        <li><a href="#">{{ user.username }}</a></li>
        <li><a href="/accounts/logout">logout</a></li>
    {% else %}
        <li><a href="/accounts/login">Log In</a></li>
    {% endif %}
</ul><!-- /.info -->
<br>
<br>
<br>

templates/new_photo.html
{% extends "layout2.html" %}

{% block content %}

<h1> hi 나는 new포토야</h1>

{% endblock %}

templates/photo.html
{% extends 'layout.html' %}

{% block content %}
<p>hello world</p>

<p>{{photo.image_file.url}}</p>

<p><img src="{{photo.image_file.url}}" /></p>
{% endblock %}